/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../common";

export declare namespace Marketplace {
  export type CollectibleStruct = {
    id: PromiseOrValue<BigNumberish>;
    collectionId: PromiseOrValue<BigNumberish>;
    tokenIds: PromiseOrValue<BigNumberish>[];
    owner: PromiseOrValue<string>;
    creator: PromiseOrValue<string>;
    isAuction: PromiseOrValue<boolean>;
    nftAuction: PromiseOrValue<string>;
  };

  export type CollectibleStructOutput = [
    BigNumber,
    BigNumber,
    BigNumber[],
    string,
    string,
    boolean,
    string
  ] & {
    id: BigNumber;
    collectionId: BigNumber;
    tokenIds: BigNumber[];
    owner: string;
    creator: string;
    isAuction: boolean;
    nftAuction: string;
  };

  export type CollectionStruct = {
    name: PromiseOrValue<string>;
    symbol: PromiseOrValue<string>;
    description: PromiseOrValue<string>;
    nftCollection: PromiseOrValue<string>;
    fee: PromiseOrValue<BigNumberish>;
    price: PromiseOrValue<BigNumberish>;
    owner: PromiseOrValue<string>;
    creator: PromiseOrValue<string>;
    isApproved: PromiseOrValue<boolean>;
    isLocked: PromiseOrValue<boolean>;
  };

  export type CollectionStructOutput = [
    string,
    string,
    string,
    string,
    BigNumber,
    BigNumber,
    string,
    string,
    boolean,
    boolean
  ] & {
    name: string;
    symbol: string;
    description: string;
    nftCollection: string;
    fee: BigNumber;
    price: BigNumber;
    owner: string;
    creator: string;
    isApproved: boolean;
    isLocked: boolean;
  };
}

export interface MarketplaceInterface extends utils.Interface {
  functions: {
    "createCollectible(uint256[],uint256,bool,address)": FunctionFragment;
    "createCollection(string,string,string,uint256,uint256,address,address)": FunctionFragment;
    "editCollection(uint256,string,string,string,uint256,uint256,address,address)": FunctionFragment;
    "endAuction(uint256,uint256)": FunctionFragment;
    "getCollectible(uint256,uint256)": FunctionFragment;
    "getCollectibleCount(uint256)": FunctionFragment;
    "getCollection(uint256)": FunctionFragment;
    "getCollectionBySymbol(string)": FunctionFragment;
    "getCollectionCounter()": FunctionFragment;
    "getCollectionIdByName(string)": FunctionFragment;
    "getFee()": FunctionFragment;
    "getName()": FunctionFragment;
    "getOwner()": FunctionFragment;
    "getUserFunds(address)": FunctionFragment;
    "setFee(uint256)": FunctionFragment;
    "setName(string)": FunctionFragment;
    "startAuction(uint256,uint256)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "createCollectible"
      | "createCollection"
      | "editCollection"
      | "endAuction"
      | "getCollectible"
      | "getCollectibleCount"
      | "getCollection"
      | "getCollectionBySymbol"
      | "getCollectionCounter"
      | "getCollectionIdByName"
      | "getFee"
      | "getName"
      | "getOwner"
      | "getUserFunds"
      | "setFee"
      | "setName"
      | "startAuction"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "createCollectible",
    values: [
      PromiseOrValue<BigNumberish>[],
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<boolean>,
      PromiseOrValue<string>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "createCollection",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      PromiseOrValue<string>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "editCollection",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      PromiseOrValue<string>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "endAuction",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getCollectible",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getCollectibleCount",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getCollection",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getCollectionBySymbol",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "getCollectionCounter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getCollectionIdByName",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(functionFragment: "getFee", values?: undefined): string;
  encodeFunctionData(functionFragment: "getName", values?: undefined): string;
  encodeFunctionData(functionFragment: "getOwner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getUserFunds",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "setFee",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "setName",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "startAuction",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
  ): string;

  decodeFunctionResult(
    functionFragment: "createCollectible",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createCollection",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "editCollection",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "endAuction", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getCollectible",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCollectibleCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCollection",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCollectionBySymbol",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCollectionCounter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCollectionIdByName",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getFee", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getName", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getOwner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getUserFunds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setFee", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setName", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "startAuction",
    data: BytesLike
  ): Result;

  events: {
    "CreateCollectible(uint256,uint256,uint256[],address,address,bool,address)": EventFragment;
    "CreateCollection(uint256,string,string,uint256,uint256,address,address,address)": EventFragment;
    "EditCollection(uint256,string,string,uint256,address,address,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "CreateCollectible"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "CreateCollection"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "EditCollection"): EventFragment;
}

export interface CreateCollectibleEventObject {
  id: BigNumber;
  collectionId: BigNumber;
  tokenIds: BigNumber[];
  owner: string;
  creator: string;
  isAuction: boolean;
  auction: string;
}
export type CreateCollectibleEvent = TypedEvent<
  [BigNumber, BigNumber, BigNumber[], string, string, boolean, string],
  CreateCollectibleEventObject
>;

export type CreateCollectibleEventFilter =
  TypedEventFilter<CreateCollectibleEvent>;

export interface CreateCollectionEventObject {
  id: BigNumber;
  name: string;
  symbol: string;
  fee: BigNumber;
  price: BigNumber;
  collection: string;
  creator: string;
  owner: string;
}
export type CreateCollectionEvent = TypedEvent<
  [BigNumber, string, string, BigNumber, BigNumber, string, string, string],
  CreateCollectionEventObject
>;

export type CreateCollectionEventFilter =
  TypedEventFilter<CreateCollectionEvent>;

export interface EditCollectionEventObject {
  id: BigNumber;
  name: string;
  symbol: string;
  fee: BigNumber;
  collection: string;
  creator: string;
  owner: string;
}
export type EditCollectionEvent = TypedEvent<
  [BigNumber, string, string, BigNumber, string, string, string],
  EditCollectionEventObject
>;

export type EditCollectionEventFilter = TypedEventFilter<EditCollectionEvent>;

export interface Marketplace extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: MarketplaceInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    createCollectible(
      _tokenIds: PromiseOrValue<BigNumberish>[],
      _collectionId: PromiseOrValue<BigNumberish>,
      _isAuction: PromiseOrValue<boolean>,
      _nftAuction: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    createCollection(
      name: PromiseOrValue<string>,
      symbol: PromiseOrValue<string>,
      description: PromiseOrValue<string>,
      fee: PromiseOrValue<BigNumberish>,
      price: PromiseOrValue<BigNumberish>,
      nftCollection: PromiseOrValue<string>,
      owner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    editCollection(
      id: PromiseOrValue<BigNumberish>,
      name: PromiseOrValue<string>,
      symbol: PromiseOrValue<string>,
      description: PromiseOrValue<string>,
      fee: PromiseOrValue<BigNumberish>,
      price: PromiseOrValue<BigNumberish>,
      nftCollection: PromiseOrValue<string>,
      owner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    endAuction(
      _collectionId: PromiseOrValue<BigNumberish>,
      _collectibleId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    getCollectible(
      _collectionId: PromiseOrValue<BigNumberish>,
      _collectibleId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[Marketplace.CollectibleStructOutput]>;

    getCollectibleCount(
      _collectionId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getCollection(
      _collectionId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[Marketplace.CollectionStructOutput]>;

    getCollectionBySymbol(
      _collectionSymbol: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[Marketplace.CollectionStructOutput]>;

    getCollectionCounter(overrides?: CallOverrides): Promise<[BigNumber]>;

    getCollectionIdByName(
      _collectionName: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getFee(overrides?: CallOverrides): Promise<[BigNumber]>;

    getName(overrides?: CallOverrides): Promise<[string]>;

    getOwner(overrides?: CallOverrides): Promise<[string]>;

    getUserFunds(
      _address: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    setFee(
      _marketFee: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setName(
      _marketName: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    startAuction(
      _collectionId: PromiseOrValue<BigNumberish>,
      _collectibleId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  createCollectible(
    _tokenIds: PromiseOrValue<BigNumberish>[],
    _collectionId: PromiseOrValue<BigNumberish>,
    _isAuction: PromiseOrValue<boolean>,
    _nftAuction: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  createCollection(
    name: PromiseOrValue<string>,
    symbol: PromiseOrValue<string>,
    description: PromiseOrValue<string>,
    fee: PromiseOrValue<BigNumberish>,
    price: PromiseOrValue<BigNumberish>,
    nftCollection: PromiseOrValue<string>,
    owner: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  editCollection(
    id: PromiseOrValue<BigNumberish>,
    name: PromiseOrValue<string>,
    symbol: PromiseOrValue<string>,
    description: PromiseOrValue<string>,
    fee: PromiseOrValue<BigNumberish>,
    price: PromiseOrValue<BigNumberish>,
    nftCollection: PromiseOrValue<string>,
    owner: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  endAuction(
    _collectionId: PromiseOrValue<BigNumberish>,
    _collectibleId: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  getCollectible(
    _collectionId: PromiseOrValue<BigNumberish>,
    _collectibleId: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<Marketplace.CollectibleStructOutput>;

  getCollectibleCount(
    _collectionId: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getCollection(
    _collectionId: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<Marketplace.CollectionStructOutput>;

  getCollectionBySymbol(
    _collectionSymbol: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<Marketplace.CollectionStructOutput>;

  getCollectionCounter(overrides?: CallOverrides): Promise<BigNumber>;

  getCollectionIdByName(
    _collectionName: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getFee(overrides?: CallOverrides): Promise<BigNumber>;

  getName(overrides?: CallOverrides): Promise<string>;

  getOwner(overrides?: CallOverrides): Promise<string>;

  getUserFunds(
    _address: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  setFee(
    _marketFee: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setName(
    _marketName: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  startAuction(
    _collectionId: PromiseOrValue<BigNumberish>,
    _collectibleId: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    createCollectible(
      _tokenIds: PromiseOrValue<BigNumberish>[],
      _collectionId: PromiseOrValue<BigNumberish>,
      _isAuction: PromiseOrValue<boolean>,
      _nftAuction: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    createCollection(
      name: PromiseOrValue<string>,
      symbol: PromiseOrValue<string>,
      description: PromiseOrValue<string>,
      fee: PromiseOrValue<BigNumberish>,
      price: PromiseOrValue<BigNumberish>,
      nftCollection: PromiseOrValue<string>,
      owner: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    editCollection(
      id: PromiseOrValue<BigNumberish>,
      name: PromiseOrValue<string>,
      symbol: PromiseOrValue<string>,
      description: PromiseOrValue<string>,
      fee: PromiseOrValue<BigNumberish>,
      price: PromiseOrValue<BigNumberish>,
      nftCollection: PromiseOrValue<string>,
      owner: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    endAuction(
      _collectionId: PromiseOrValue<BigNumberish>,
      _collectibleId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    getCollectible(
      _collectionId: PromiseOrValue<BigNumberish>,
      _collectibleId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<Marketplace.CollectibleStructOutput>;

    getCollectibleCount(
      _collectionId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getCollection(
      _collectionId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<Marketplace.CollectionStructOutput>;

    getCollectionBySymbol(
      _collectionSymbol: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<Marketplace.CollectionStructOutput>;

    getCollectionCounter(overrides?: CallOverrides): Promise<BigNumber>;

    getCollectionIdByName(
      _collectionName: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getFee(overrides?: CallOverrides): Promise<BigNumber>;

    getName(overrides?: CallOverrides): Promise<string>;

    getOwner(overrides?: CallOverrides): Promise<string>;

    getUserFunds(
      _address: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    setFee(
      _marketFee: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    setName(
      _marketName: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    startAuction(
      _collectionId: PromiseOrValue<BigNumberish>,
      _collectibleId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "CreateCollectible(uint256,uint256,uint256[],address,address,bool,address)"(
      id?: null,
      collectionId?: null,
      tokenIds?: null,
      owner?: PromiseOrValue<string> | null,
      creator?: PromiseOrValue<string> | null,
      isAuction?: null,
      auction?: PromiseOrValue<string> | null
    ): CreateCollectibleEventFilter;
    CreateCollectible(
      id?: null,
      collectionId?: null,
      tokenIds?: null,
      owner?: PromiseOrValue<string> | null,
      creator?: PromiseOrValue<string> | null,
      isAuction?: null,
      auction?: PromiseOrValue<string> | null
    ): CreateCollectibleEventFilter;

    "CreateCollection(uint256,string,string,uint256,uint256,address,address,address)"(
      id?: null,
      name?: null,
      symbol?: null,
      fee?: null,
      price?: null,
      collection?: PromiseOrValue<string> | null,
      creator?: PromiseOrValue<string> | null,
      owner?: PromiseOrValue<string> | null
    ): CreateCollectionEventFilter;
    CreateCollection(
      id?: null,
      name?: null,
      symbol?: null,
      fee?: null,
      price?: null,
      collection?: PromiseOrValue<string> | null,
      creator?: PromiseOrValue<string> | null,
      owner?: PromiseOrValue<string> | null
    ): CreateCollectionEventFilter;

    "EditCollection(uint256,string,string,uint256,address,address,address)"(
      id?: null,
      name?: null,
      symbol?: null,
      fee?: null,
      collection?: PromiseOrValue<string> | null,
      creator?: PromiseOrValue<string> | null,
      owner?: PromiseOrValue<string> | null
    ): EditCollectionEventFilter;
    EditCollection(
      id?: null,
      name?: null,
      symbol?: null,
      fee?: null,
      collection?: PromiseOrValue<string> | null,
      creator?: PromiseOrValue<string> | null,
      owner?: PromiseOrValue<string> | null
    ): EditCollectionEventFilter;
  };

  estimateGas: {
    createCollectible(
      _tokenIds: PromiseOrValue<BigNumberish>[],
      _collectionId: PromiseOrValue<BigNumberish>,
      _isAuction: PromiseOrValue<boolean>,
      _nftAuction: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    createCollection(
      name: PromiseOrValue<string>,
      symbol: PromiseOrValue<string>,
      description: PromiseOrValue<string>,
      fee: PromiseOrValue<BigNumberish>,
      price: PromiseOrValue<BigNumberish>,
      nftCollection: PromiseOrValue<string>,
      owner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    editCollection(
      id: PromiseOrValue<BigNumberish>,
      name: PromiseOrValue<string>,
      symbol: PromiseOrValue<string>,
      description: PromiseOrValue<string>,
      fee: PromiseOrValue<BigNumberish>,
      price: PromiseOrValue<BigNumberish>,
      nftCollection: PromiseOrValue<string>,
      owner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    endAuction(
      _collectionId: PromiseOrValue<BigNumberish>,
      _collectibleId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    getCollectible(
      _collectionId: PromiseOrValue<BigNumberish>,
      _collectibleId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getCollectibleCount(
      _collectionId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getCollection(
      _collectionId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getCollectionBySymbol(
      _collectionSymbol: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getCollectionCounter(overrides?: CallOverrides): Promise<BigNumber>;

    getCollectionIdByName(
      _collectionName: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getFee(overrides?: CallOverrides): Promise<BigNumber>;

    getName(overrides?: CallOverrides): Promise<BigNumber>;

    getOwner(overrides?: CallOverrides): Promise<BigNumber>;

    getUserFunds(
      _address: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    setFee(
      _marketFee: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setName(
      _marketName: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    startAuction(
      _collectionId: PromiseOrValue<BigNumberish>,
      _collectibleId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    createCollectible(
      _tokenIds: PromiseOrValue<BigNumberish>[],
      _collectionId: PromiseOrValue<BigNumberish>,
      _isAuction: PromiseOrValue<boolean>,
      _nftAuction: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    createCollection(
      name: PromiseOrValue<string>,
      symbol: PromiseOrValue<string>,
      description: PromiseOrValue<string>,
      fee: PromiseOrValue<BigNumberish>,
      price: PromiseOrValue<BigNumberish>,
      nftCollection: PromiseOrValue<string>,
      owner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    editCollection(
      id: PromiseOrValue<BigNumberish>,
      name: PromiseOrValue<string>,
      symbol: PromiseOrValue<string>,
      description: PromiseOrValue<string>,
      fee: PromiseOrValue<BigNumberish>,
      price: PromiseOrValue<BigNumberish>,
      nftCollection: PromiseOrValue<string>,
      owner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    endAuction(
      _collectionId: PromiseOrValue<BigNumberish>,
      _collectibleId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    getCollectible(
      _collectionId: PromiseOrValue<BigNumberish>,
      _collectibleId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getCollectibleCount(
      _collectionId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getCollection(
      _collectionId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getCollectionBySymbol(
      _collectionSymbol: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getCollectionCounter(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getCollectionIdByName(
      _collectionName: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getFee(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getName(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getOwner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getUserFunds(
      _address: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    setFee(
      _marketFee: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setName(
      _marketName: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    startAuction(
      _collectionId: PromiseOrValue<BigNumberish>,
      _collectibleId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
